name: Build
on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main, actions ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 17 2022"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build lua-debug
        id: setup
        shell: python
        run: |
          import subprocess
          import os

          tmp_env = os.environ.copy()
          curdir = os.getcwd()
          subprocess.run(["git","clone","https://github.com/actboy168/luamake"],shell=True,check=True,env=tmp_env)
          luamake_root = os.getcwd() +"/luamake"
          os.chdir(luamake_root)
          subprocess.run(["git","submodule","init"],shell=True,check=True,env=tmp_env)
          subprocess.run(["git","submodule","update"],shell=True,check=True,env=tmp_env)
          subprocess.run([luamake_root +"/compile/install.bat"],shell=True,check=True,env=tmp_env)

          os.chdir(curdir)
          subprocess.run(["git","clone","https://github.com/actboy168/lua-debug"],shell=True,check=True,env=tmp_env)
          subprocess.run(["cd","lua-debug"],shell=True,check=True,env=tmp_env)
          subprocess.run(["git","submodule","init"],shell=True,check=True,env=tmp_env)
          subprocess.run(["git","submodule","update"],shell=True,check=True,env=tmp_env)

          tmp_env["PATH"] = luamake_root +";" + tmp_env["PATH"]
          #os.environ["PATH"] += os.pathsep + luamake_root
          subprocess.run(["luamake","lua","compile/download_deps.lua"],shell=True,check=True,env=tmp_env)
          subprocess.run(["luamake"],shell=True,check=True,env=tmp_env)

          #git clone https://github.com/actboy168/luamake
          #pushd luamake
          #git submodule init
          #git submodule update
          #./compile/install.bat
          #$currentDir = Get-Location
          #$env:Path += ';' + $currentDir
          #popd

          #git clone https://github.com/actboy168/lua-debug
          #cd lua-debug
          #git submodule init
          #git submodule update

          #luamake lua compile/download_deps.lua
          #luamake
          