name: Build
on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main, actions ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            artifact: "Windows-MSVC.tar.xz"
            generators: "Visual Studio 17 2022"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build lua-debug
        id: setup
        shell: bash
        run: |
          git clone https://github.com/actboy168/luamake
          pushd luamake
          git submodule init
          git submodule update
          .\compile\install.bat
          popd

          git clone https://github.com/actboy168/lua-debug
          cd lua-debug
          git submodule init
          git submodule update
          